baseURL = "https://www.jujitsukeerbergen.be"
#baseURL = "https://eager-galileo-efb33e.netlify.com"
languageCode = "nl-BE"
title = "Ju-Jitsu Keerbergen VZW"
clubName = "Ju-Jitsu Keerbergen VZW"
paginate = 8
theme = "txt"
hasCJKLanguage=true

[permalinks]
    nieuws = "/:section/:year/:month/:day/:slug/"

[params]
dateForm = "January 2, 2006"

# Variables For Site Navigation

[[menu.global]]
    name = "Wat is Ju-Jitsu"
    identifier = ""
    url = "/jujitsu"
    weight = 1

[[menu.global]]
    name = "Wie zijn wij"
    identifier = ""
    url = "/trainers"
    weight = 5

[[menu.global]]
    name = "Club"
    identifier = "club"
    url = "/club"
    weight = 10


[[menu.global]]
    name = "Lidmaatschap & Training"
    identifier = "lidmaatschap-training"
    url = "/lidmaatschap-training"
    weight = 15

[[menu.global]]
    name = "Nieuws"
    identifier = "nieuws"
    url = "/nieuws"
    weight = 20

[[menu.global]]
    name = "Kalender"
    identifier = "kalender"
    url = "/kalender"
    weight = 30

[[menu.global]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"
    weight = 40

[[menu.global]]
    name = "Links"
    identifier = "links"
    url = "/links"
    weight = 160

# Variables for out of site navigation

[[params.social]]
	icon = "fa-facebook"
    name = "Facebook"
	url = "https://www.facebook.com/groups/357231384348318/"
    weight = 1

[[params.social]]
	icon = "fa-instagram"
    name = "Instagram"
	url = "http://instagram.com/jujitsukeerbergen"
    weight = 3

[[params.social]]
    icon = "fa-twitter"
    name = "Twitter"
	url = "https://twitter.com/jjkeerbergen"
    weight = 5

[[params.social]]
    icon = "fa-mail-forward"
    name = "Email"
	url = "mailto:info@jujitsukeerbergen.be"
    weight = 10