[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.37.1"

[context.draft]
  command = "hugo -b $DEPLOY_PRIME_URL --buildDrafts --buildFuture"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"